[package]
name = "devcaders"
version = "0.1.0"
edition = "2021"
description = "Devcade input support library for Bevy+Rust!"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.0"
enum-iterator = "1.4.0"
